# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys4_Master.xdc

# Block Designs: bd/fbRAM/fbRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fbRAM || ORIG_REF_NAME==fbRAM}]

# IP: bd/fbRAM/ip/fbRAM_blk_mem_gen_0_0/fbRAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fbRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==fbRAM_blk_mem_gen_0_0}]

# Block Designs: bd/vector_ram/vector_ram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_ram || ORIG_REF_NAME==vector_ram}]

# IP: bd/vector_ram/ip/vector_ram_blk_mem_gen_0_0/vector_ram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_ram_blk_mem_gen_0_0 || ORIG_REF_NAME==vector_ram_blk_mem_gen_0_0}]

# Block Designs: bd/prog_ROM/prog_ROM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prog_ROM || ORIG_REF_NAME==prog_ROM}]

# IP: bd/prog_ROM/ip/prog_ROM_blk_mem_gen_0_0/prog_ROM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prog_ROM_blk_mem_gen_0_0 || ORIG_REF_NAME==prog_ROM_blk_mem_gen_0_0}]

# Block Designs: bd/prog_RAM/prog_RAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prog_RAM || ORIG_REF_NAME==prog_RAM}]

# IP: bd/prog_RAM/ip/prog_RAM_blk_mem_gen_0_0/prog_RAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prog_RAM_blk_mem_gen_0_0 || ORIG_REF_NAME==prog_RAM_blk_mem_gen_0_0}]

# XDC: bd/fbRAM/ip/fbRAM_blk_mem_gen_0_0/fbRAM_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/fbRAM/fbRAM_ooc.xdc

# XDC: bd/vector_ram/ip/vector_ram_blk_mem_gen_0_0/vector_ram_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/vector_ram/vector_ram_ooc.xdc

# XDC: bd/prog_ROM/ip/prog_ROM_blk_mem_gen_0_0/prog_ROM_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/prog_ROM/prog_ROM_ooc.xdc

# XDC: bd/prog_RAM/ip/prog_RAM_blk_mem_gen_0_0/prog_RAM_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/prog_RAM/prog_RAM_ooc.xdc
