# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/prog_rom.coe
add_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/mem_dump_draw.coe
add_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/blankRam.coe
read_verilog {
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/avg_defines.vh
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/coreInterface.vh
}
add_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/fbRAM/fbRAM.bd
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/fbRAM/ip/fbRAM_blk_mem_gen_0_0/fbRAM_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/fbRAM/fbRAM_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/fbRAM/fbRAM.bd]

add_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/vector_ram/vector_ram.bd
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/vector_ram/ip/vector_ram_blk_mem_gen_0_0/vector_ram_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/vector_ram/vector_ram_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/vector_ram/vector_ram.bd]

add_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/prog_ROM/prog_ROM.bd
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/prog_ROM/ip/prog_ROM_blk_mem_gen_0_0/prog_ROM_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/prog_ROM/prog_ROM_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/prog_ROM/prog_ROM.bd]

add_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/prog_RAM/prog_RAM.bd
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/prog_RAM/ip/prog_RAM_blk_mem_gen_0_0/prog_RAM_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/prog_RAM/prog_RAM_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/prog_RAM/prog_RAM.bd]

read_verilog -library xil_defaultlib -sv {
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/avg_decode.sv
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/matoro.sv
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/avg.sv
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/coreInterface.sv
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/VGA_fsm.sv
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/rasterizer.sv
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/fb_controller.sv
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/new/top.sv
}
read_verilog -library xil_defaultlib {
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/ALU.v
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/fbRAM/hdl/fbRAM_wrapper.v
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/vector_ram/hdl/vector_ram_wrapper.v
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/prog_ROM/hdl/prog_ROM_wrapper.v
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/sources_1/bd/prog_RAM/hdl/prog_RAM_wrapper.v
  /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/cpu.v
}
read_xdc /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/constrs_1/new/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/ashresth/Private/545proj/F15_18545_BattleZone/code/6502/GameCore/GameCore.srcs/constrs_1/new/Nexys4_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top -part xc7a100tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
