# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /afs/ece.cmu.edu/usr/htay/frame_buffer/Nexys4_Master.xdc

# Block Designs: bd/blockRam/blockRam.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blockRam || ORIG_REF_NAME==blockRam}]

# IP: bd/blockRam/ip/blockRam_blk_mem_gen_0_0/blockRam_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blockRam_blk_mem_gen_0_0 || ORIG_REF_NAME==blockRam_blk_mem_gen_0_0}]

# XDC: bd/blockRam/ip/blockRam_blk_mem_gen_0_0/blockRam_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/blockRam/blockRam_ooc.xdc
