# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/bd/blockRam/blockRam.bd
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/bd/blockRam/ip/blockRam_blk_mem_gen_0_0/blockRam_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/bd/blockRam/blockRam_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/bd/blockRam/blockRam.bd]

read_verilog -library xil_defaultlib -sv {
  /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/new/fb_top.sv
  /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/new/fb_controller.sv
  /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/new/VGA_fsm.sv
  /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/new/shapes_tb.sv
  /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/new/matoro.sv
  /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/new/rasterizer.sv
}
read_verilog -library xil_defaultlib /afs/ece.cmu.edu/usr/htay/frame_buffer/frame_buffer.srcs/sources_1/bd/blockRam/hdl/blockRam_wrapper.v
read_xdc /afs/ece.cmu.edu/usr/htay/frame_buffer/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/htay/frame_buffer/Nexys4_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top fb_top -part xc7a100tcsg324-1
write_checkpoint -noxdef fb_top.dcp
catch { report_utilization -file fb_top_utilization_synth.rpt -pb fb_top_utilization_synth.pb }
